### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by makorne** [ypid/ansible-cryptsetup_remote_unlock#4]
https://github.com/debops-contrib/ansible-dropbear_initramfs/blob/master/docs/getting-started.rst#id1:
```
If you are using DebOps, you can set the following in your inventory:

## Load APT pinning presets.
apt_preferences__group_list:
  - '{{ apt_preferences__preset_list | list }}'

apt__group_sources:
  - comment: 'Enable Debian stretch repository'
    uri: '{{ ansible_local.apt.default_sources_map.Debian[0]
             if (ansible_local|d() and ansible_local.apt|d() and
                 ansible_local.apt.default_sources_map|d() and
                 ansible_local.apt.default_sources_map.Debian|d() and
                 ansible_local.apt.default_sources_map.Debian[0]|d())
             else "http://deb.debian.org/debian" }}'
    suites:
      - 'stretch'
    component:
      - 'main'

dropbear_initramfs__base_packages:
  - 'dropbear-initramfs'
```

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/project-directory/ansible/playbooks/dropbear_initramfs.yml': line 27, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - comment: 'Enable Debian stretch repository'
    uri: '{{ ansible_local.apt.default_sources_map.Debian[0]
    ^ here
This one looks easy to fix.  It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote.  For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"
```

**Comment by ypid** [comment]
@makorne In YAML, indention is important. Do you see the issue when you compare:

```YAML
    - comment: 'Enable Debian stretch repository'
    uri: '{{ ansible_local.apt.default_sources_map.Debian[0]
```

to:

https://raw.githubusercontent.com/debops-contrib/ansible-dropbear_initramfs/master/docs/getting-started.rst

Please learn how YAML works. It is a basic building block of Ansible.

**Comment by makorne** [comment]
Please, how to get this work? 
Look at yum, apt so on... they dont have the loud name "playbook"! 
But they dont require to fill out many unknown files in unknown order with unknown variables from other spagetti of unknown files..  
Provided example does not work! You are the God of this code, you are the maintainer... 
And even you cant create an easy WORKING example for localhost?
Please, a real example - what files with what sources are required to get it work?
Or is that impossible to get it work?

**Comment by ypid** [comment]
The example should work you just need to get the indention for YAML correct:


```YAML
## Load APT pinning presets.
apt_preferences__group_list:
  - '{{ apt_preferences__preset_list | list }}'

apt__group_sources:
  - comment: 'Enable Debian stretch repository'
    uri: '{{ ansible_local.apt.default_sources_map.Debian[0]
             if (ansible_local|d() and ansible_local.apt|d() and
                 ansible_local.apt.default_sources_map|d() and
                 ansible_local.apt.default_sources_map.Debian|d() and
                 ansible_local.apt.default_sources_map.Debian[0]|d())
             else "http://deb.debian.org/debian" }}'
    suites:
      - 'stretch'
    component:
      - 'main'

dropbear_initramfs__base_packages:
  - 'dropbear-initramfs'
```

Again the advice to get some basic knowledge of this stuff. This role is a bit advanced as most DebOps roles. Maybe watch a good introduction talk to Ansible, write a few playbooks and maybe a small role to get familiar with how this is supposed to work. After that you should be able to get up and running with this role.

**Comment by makorne** [comment]
nano /root/project-directory/ansible/playbooks/dropbear_initramfs.yml
```
- name: Setup the dropbear ssh server in initramfs
  hosts: [ myhost, 'debops_service_dropbear_initramfs' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ dropbear_initramfs__apt_preferences__dependent_list }}'

    - role: debops-contrib.dropbear_initramfs
      tags: [ 'role::dropbear_initramfs' ]

## Load APT pinning presets.
apt_preferences__group_list:
  - '{{ apt_preferences__preset_list | list }}'

apt__group_sources:
  - comment: 'Enable Debian stretch repository'
    uri: '{{ ansible_local.apt.default_sources_map.Debian[0]
             if (ansible_local|d() and ansible_local.apt|d() and
                 ansible_local.apt.default_sources_map|d() and
                 ansible_local.apt.default_sources_map.Debian|d() and
                 ansible_local.apt.default_sources_map.Debian[0]|d())
             else "http://deb.debian.org/debian" }}'
    suites:
      - 'stretch'
    component:
      - 'main'

dropbear_initramfs__base_packages:
  - 'dropbear-initramfs'
  [debops_service_dropbear_initramfs]
  myhost
```
ansible-playbook /root/project-directory/ansible/playbooks/dropbear_initramfs.yml -vvvv
```
SUDO password[defaults to SSH password]: 
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/project-directory/ansible/playbooks/dropbear_initramfs.yml': line 22, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

## Load APT pinning presets.
apt_preferences__group_list:
^ here
```
